<?php
namespace BetFormulaBundle\Entity;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GpRepository extends \Doctrine\ORM\EntityRepository
{
    function nextGp() {
        return $this->createQueryBuilder('g')
                ->where('g.gpDate > CURRENT_TIMESTAMP()')
                ->addOrderBy('g.gpDate', "ASC")
                ->setMaxResults(1)
                ->getQuery()
                ->getOneOrNullResult();
    }
}